CREATE TABLE `AMP_ENVIRONMENT` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT NOW() COMMENT '更新时间',
    `CREATE_AT` VARCHAR(32) NOT NULL DEFAULT 'SYS' COMMENT '创建人',
    `UPDATE_AT` VARCHAR(32) NOT NULL DEFAULT 'SYS' COMMENT '最后一次更新人',
    `UNIQUE_TOKEN` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '是否删除，0-未删除，其他-删除',
    `ENVIRONMENT_NAME` VARCHAR(64) NOT NULL COMMENT '环境名称',
    `ENVIRONMENT_DESC` VARCHAR(256) COMMENT '环境描述',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_ENVIRONMENT_NAME` (`ENVIRONMENT_NAME`, `UNIQUE_TOKEN`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='环境信息表';