CREATE TABLE `AMP_CONFIG_SYNC_RECORD` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `CREATE_AT` varchar(32) NOT NULL DEFAULT 'SYS' COMMENT '创建人',
    `UPDATE_AT` varchar(32) NOT NULL DEFAULT 'SYS' COMMENT '最后一次更新人',
    `UNIQUE_TOKEN` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除，0-未删除，其他-删除',
    `APP_NAME` varchar(64) NOT NULL COMMENT '应用名称',
    `ENVIRONMENT` varchar(256) NOT NULL COMMENT '环境',
    `COLONY_NAME` varchar(64) NOT NULL COMMENT '配置项KEY',
    `STATUS` varchar(32) NOT NULL COMMON '同步状态',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_APP_COLONY` (`APP_NAME`,`COLONY_NAME`,`UNIQUE_TOKEN`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='配置项同步记录表'