CREATE TABLE `AMP_COLONY_CONFIG` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT NOW() COMMENT '更新时间',
    `CREATE_AT` VARCHAR(32) NOT NULL DEFAULT 'SYS' COMMENT '创建人',
    `UPDATE_AT` VARCHAR(32) NOT NULL DEFAULT 'SYS' COMMENT '最后一次更新人',
    `UNIQUE_TOKEN` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '是否删除，0-未删除，其他-删除',
    `COLONY_NAME` VARCHAR(64) NOT NULL COMMENT '环境名称',
    `CONFIG_KEY` VARCHAR(128) NOT NULL COMMENT '配置项',
    `CONFIG_VALUE` VARCHAR(512) COMMENT '配置项值',
    `CONFIG_DESC` VARCHAR(512) COMMENT '配置项描述',
    `APP_NAME` VARCHAR(32) NOT NULL COMMENT '应用名称',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_ARTICLE_ID_SOURCE` (`CONFIG_KEY`,`COLONY_NAME`),
    INDEX `IDX_APP_NAME` (`APP_NAME`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='集群配置表';