CREATE TABLE `AMP_CONFIG_ITEM` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `CREATE_AT` varchar(32) NOT NULL DEFAULT 'SYS' COMMENT '创建人',
    `UPDATE_AT` varchar(32) NOT NULL DEFAULT 'SYS' COMMENT '最后一次更新人',
    `UNIQUE_TOKEN` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否删除，0-未删除，其他-删除',
    `APPLICATION_ID` bigint(20) NOT NULL COMMENT '应用ID',
    `APPLICATION_NAME` varchar(64) NOT NULL COMMENT '应用名称',
    `ENVIRONMENT` varchar(256) NOT NULL COMMENT '环境',
    `CONFIG_KEY` varchar(512) NOT NULL COMMENT '配置项KEY',
    `CONFIG_VALUE` varchar(4000) NOT NULL COMMENT '配置项VALUE',
    `CONFIG_TYPE` varchar(64) NOT NULL COMMENT '配置项类型',
    `CONFIG_DESC` varchar(256) DEFAULT NULL COMMENT '描述',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `AMP_APP_ENV_CONFIG` (`APPLICATION_NAME`,`ENVIRONMENT`,`CONFIG_KEY`),
    UNIQUE KEY `AMP_APP_ID_ENV_CONFIG` (`APPLICATION_ID`,`ENVIRONMENT`,`CONFIG_KEY`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='配置项存储表'