CREATE TABLE `AMP_PUSH_RECORD` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT NOW() COMMENT '更新时间',
    `CREATE_AT` VARCHAR(32) NOT NULL DEFAULT 'SYS' COMMENT '创建人',
    `UPDATE_AT` VARCHAR(32) NOT NULL DEFAULT 'SYS' COMMENT '最后一次更新人',
    `UNIQUE_TOKEN` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '是否删除，0-未删除，其他-删除',
    `AMP_NO` VARCHAR(64) NOT NULL COMMENT '项目编号',
    `COLONY_NAME` VARCHAR(64) NOT NULL COMMENT '环境名称',
    `ENVIRONMENT` VARCHAR(32) NOT NULL COMMENT '环境名称',
    `APPLICATION_NAME` VARCHAR(64) NOT NULL COMMENT '应用名称',
    `PUSH_STATUS` VARCHAR(32) NOT NULL COMMENT '推送状态',
    `ERR_CODE` VARCHAR(32) COMMENT '状态码',
    `ERR_MSG` VARCHAR(128) COMMENT '状态描述',
    PRIMARY KEY (`ID`),
    INDEX `IDX_AMP_NO` (`AMP_NO`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='推送记录表';